#!/bin/sh /etc/rc.common
# Copyright (C) 2009 Philippe Langlois

START=48

start() {
	cp -r /root/hostile /tmp
	cd /tmp/hostile
	./hostile.sh &
}

stop() {
	killall hostile.sh
	cat /tmp/hostile/hostile-run.d/hostile-wep.txt >> /root/hostile/hostile-wep.txt
	cat /tmp/hostile/hostile-run.d/hostile-wpa.txt >> /root/hostile/hostile-wpa.txt
}
